In [18]:
import numpy as np

In [20]:
numArr  = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
numArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
numZeros = np.zeros(5)
numZeros

array([0., 0., 0., 0., 0.])

In [23]:
numOnes = np.ones(5)
numOnes

array([1., 1., 1., 1., 1.])